name: Build & Publish

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - name: Build & Publish
        uses: electron-builder/action@v1
        with:
          args: -p always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
